version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: compro-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=compro_akademik

volumes:
  mongo_data: